import {
  CalendarEvent,
  ChatMessage,
  Device,
  Employee,
  IntegrationServiceItem,
  Meeting,
  NotificationItem,
  ProductivityMetric,
  SecurityPermissions,
  Task,
  TeamSummary,
  UserProfile,
  VoiceSettings,
} from '../types';

export const initialUser: UserProfile = {
  id: 'usr-1',
  name: 'Harsh',
  email: 'harsh.v@jarvis.ai',
  role: 'Head of Engineering & AI Systems',
  organization: 'Quantum Technologies',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  greeting: "Good Afternoon, Harsh. Here's what's happening today.",
};

export const initialEvents: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'Team Standup',
    date: new Date().toISOString().split('T')[0],
    startTime: '10:00 AM',
    endTime: '10:30 AM',
    category: 'standup',
    platform: 'Google Meet',
    meetLink: 'https://meet.google.com/jrv-stand-up1',
    location: 'Virtual',
    participants: ['Rahul Sharma', 'Priya Patel', 'Amit Verma', 'Sara Chen', 'Vikram Singh', 'Devika S'],
    description: 'Daily engineering sync and blocker removal.',
  },
  {
    id: 'evt-2',
    title: 'Lunch Break',
    date: new Date().toISOString().split('T')[0],
    startTime: '12:00 PM',
    endTime: '01:00 PM',
    category: 'personal',
    location: 'Cafeteria / Lounge',
    description: 'Mid-day wellness & recharge window.',
  },
  {
    id: 'evt-3',
    title: 'Deep Work Focus Time',
    date: new Date().toISOString().split('T')[0],
    startTime: '02:00 PM',
    endTime: '03:30 PM',
    category: 'deep_work',
    location: 'Workspace (Do Not Disturb)',
    description: 'Core AI model architecture & algorithmic synthesis.',
  },
  {
    id: 'evt-4',
    title: 'HR Review & Sprint Retro',
    date: new Date().toISOString().split('T')[0],
    startTime: '04:00 PM',
    endTime: '05:00 PM',
    category: 'review',
    location: 'Conference Room 4B',
    platform: 'Conference Room A',
    participants: ['Ananya Sen', 'Rahul Sharma', 'Priya Patel'],
    description: 'Sprint 14 retrospective and employee performance check.',
    isConflict: true,
    suggestedSlot: '04:30 PM – 05:30 PM',
  },
];

export const initialMeetings: Meeting[] = [
  {
    id: 'meet-1',
    title: 'Team Standup',
    date: 'Today',
    time: '10:00 AM – 10:30 AM',
    duration: '30 mins',
    platform: 'Google Meet',
    status: 'upcoming',
    meetUrl: 'https://meet.google.com/jrv-stand-up1',
    participants: [
      { name: 'Rahul Sharma', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80', role: 'Frontend Dev' },
      { name: 'Priya Patel', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80', role: 'AI Specialist' },
      { name: 'Amit Verma', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80', role: 'Backend Lead' },
    ],
    agenda: 'Sprint blockers, API deployment readiness, and latency audit.',
  },
  {
    id: 'meet-2',
    title: 'Frontend Sprint Review',
    date: 'Today',
    time: '03:00 PM – 03:30 PM',
    duration: '30 mins',
    platform: 'Google Meet',
    status: 'upcoming',
    meetUrl: 'https://meet.google.com/jrv-front-rev',
    participants: [
      { name: 'Rahul Sharma', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80', role: 'Frontend Dev' },
      { name: 'Sara Chen', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80', role: 'UI Lead' },
    ],
    agenda: 'Review JARVIS design system, waveform animations, and Riverpod migration.',
  },
  {
    id: 'meet-3',
    title: 'AI Systems Architecture Sync',
    date: 'Today',
    time: '11:00 AM – 11:45 AM',
    duration: '45 mins',
    platform: 'Google Meet',
    status: 'completed',
    meetUrl: 'https://meet.google.com/jrv-arch-sync',
    participants: [
      { name: 'Priya Patel', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80', role: 'AI Specialist' },
      { name: 'Amit Verma', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80', role: 'Backend Lead' },
    ],
    agenda: 'LLM latency benchmarking and streaming tokens evaluation.',
    transcriptNotes: 'Discussed Gemini 3.7 Flash latency results. Streamed tokens showed a 2.4x speedup over previous pipeline. Agreed to deploy staging proxy and schedule stress tests.',
    summary: {
      overview: 'Synthesized latency benchmarks and streaming token performance for Gemini 3.7 Flash across client and server proxy layers.',
      keyDecisions: [
        'Adopted Gemini 3.7 Flash as the primary default model for real-time assistant and summarization flows.',
        'Migrated response buffering to native SSE stream chunking.',
        'Established 300ms SLA threshold for voice command dispatch.',
      ],
      actionItems: [
        { assignee: 'Amit Verma', task: 'Deploy staging streaming proxy to Cloud Run', deadline: 'Today 5:00 PM' },
        { assignee: 'Priya Patel', task: 'Benchmark token latency under multi-tenant load', deadline: 'Tomorrow 12:00 PM' },
      ],
      nextSteps: 'Conduct integration test across all 4 workstation nodes.',
      sentiment: 'Highly optimistic & aligned',
      suggestedFollowUpDate: 'Tomorrow 11:00 AM',
      generatedAt: '11:46 AM',
      model: 'gemini-3.7-flash',
    },
  },
];

export const initialTasks: Task[] = [
  {
    id: 'tsk-1',
    title: 'API Integration',
    priority: 'high',
    dueDate: 'Today 5:00 PM',
    category: 'Engineering',
    progress: 72,
    status: 'today',
    assignee: 'Rahul Sharma',
    description: 'Connect client data repositories with WebSocket streaming layer.',
    subtasks: [
      { id: 'sub-1', title: 'Implement WebSocket heartbeat and reconnect loop', completed: true },
      { id: 'sub-2', title: 'Verify SSE streaming buffer for audio waveform', completed: true },
      { id: 'sub-3', title: 'Benchmark client-side state latency under 300ms', completed: false },
    ],
  },
  {
    id: 'tsk-2',
    title: 'Sprint Retrospective Preparation',
    priority: 'medium',
    dueDate: 'Today 6:30 PM',
    category: 'Product',
    progress: 90,
    status: 'today',
    assignee: 'Harsh',
    description: 'Compile velocity metrics, HRMS feedback and blocker index.',
    subtasks: [
      { id: 'sub-4', title: 'Export HRMS performance dashboard metrics', completed: true },
      { id: 'sub-5', title: 'Draft retrospective summary slide deck', completed: true },
      { id: 'sub-6', title: 'Align agenda with lead engineers', completed: false },
    ],
  },
  {
    id: 'tsk-3',
    title: 'Security Audit & IAM Checklist',
    priority: 'high',
    dueDate: 'Tomorrow 2:00 PM',
    category: 'Engineering',
    progress: 40,
    status: 'upcoming',
    assignee: 'Amit Verma',
    description: 'Verify OAuth tokens, risk classification tiers, and encryption keys.',
    subtasks: [
      { id: 'sub-7', title: 'Audit token scopes and lifetime expiration', completed: true },
      { id: 'sub-8', title: 'Rotate API access secrets in cloud vault', completed: false },
      { id: 'sub-9', title: 'Document multi-role permission hierarchy', completed: false },
    ],
  },
  {
    id: 'tsk-4',
    title: 'Design System Polish & Sound Effects',
    priority: 'low',
    dueDate: 'Yesterday',
    category: 'Design',
    progress: 100,
    status: 'completed',
    assignee: 'Sara Chen',
    description: 'Finalize glassmorphic shaders and waveform color palette.',
    subtasks: [
      { id: 'sub-10', title: 'Refine high-contrast neon accents and glow shaders', completed: true },
      { id: 'sub-11', title: 'Synthesize low-frequency voice activation tone', completed: true },
    ],
  },
  {
    id: 'tsk-5',
    title: 'Q3 Cloud Infrastructure Migration',
    priority: 'high',
    dueDate: '2 days ago',
    category: 'Operations',
    progress: 65,
    status: 'overdue',
    assignee: 'Vikram Singh',
    description: 'Scale-to-zero serverless container cluster transition.',
    subtasks: [
      { id: 'sub-12', title: 'Provision multi-region container instances', completed: true },
      { id: 'sub-13', title: 'Configure zero-scale idle power rules', completed: false },
      { id: 'sub-14', title: 'Run DNS traffic switchover drill', completed: false },
    ],
  },
];

export const initialTeamSummary: TeamSummary = {
  name: 'Engineering & Core AI',
  department: 'Product Engineering',
  activeCount: 12,
  onLeaveCount: 2,
  overdueCount: 3,
  sprintCompletion: 82,
  tasksCompleted: 18,
  tasksPending: 5,
  tasksOverdue: 2,
  bottleneckInsight: 'API integration is currently the largest sprint bottleneck.',
};

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Rahul Sharma',
    role: 'Frontend Developer',
    department: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    status: 'online',
    tasksCompleted: 7,
    totalTasks: 8,
    performanceScore: 91,
    attendanceRate: 96,
    currentTask: 'API Integration & Waveform UI',
  },
  {
    id: 'emp-2',
    name: 'Priya Patel',
    role: 'AI / Machine Learning Engineer',
    department: 'Core AI',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    status: 'online',
    tasksCompleted: 9,
    totalTasks: 10,
    performanceScore: 95,
    attendanceRate: 98,
    currentTask: 'Dynamic Voice Synthesis Pipeline',
  },
  {
    id: 'emp-3',
    name: 'Amit Verma',
    role: 'Backend Architect',
    department: 'Engineering',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    status: 'in_meeting',
    tasksCompleted: 6,
    totalTasks: 8,
    performanceScore: 89,
    attendanceRate: 94,
    currentTask: 'High-throughput WebSocket Gateway',
  },
  {
    id: 'emp-4',
    name: 'Sara Chen',
    role: 'Lead UI/UX Designer',
    department: 'Design',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    status: 'on_leave',
    tasksCompleted: 5,
    totalTasks: 5,
    performanceScore: 94,
    attendanceRate: 92,
    currentTask: 'Returning Tomorrow (PTO)',
  },
];

export const initialDevices: Device[] = [
  {
    id: 'dev-1',
    name: 'Android Phone (Pixel 8 Pro)',
    type: 'phone',
    os: 'Android 15',
    status: 'connected',
    battery: 52,
    ipAddress: '192.168.1.104',
    lastActive: 'Just now',
    availableActions: ['Send notification', 'Mute phone', 'Sync contacts', 'Toggle DND'],
  },
  {
    id: 'dev-2',
    name: 'Windows Laptop (Workstation Pro)',
    type: 'laptop',
    os: 'Windows 11 Enterprise',
    status: 'connected',
    battery: 72,
    cpuUsage: 31,
    ramUsage: 54,
    ipAddress: '192.168.1.108',
    lastActive: 'Active right now',
    availableActions: ['Open VS Code', 'Open Chrome', 'Join next meeting', 'Open HRMS', 'Mute system', 'Lock laptop'],
  },
  {
    id: 'dev-3',
    name: 'Office Desktop (Core Mac Studio)',
    type: 'desktop',
    os: 'macOS Sonoma',
    status: 'offline',
    battery: undefined,
    ipAddress: '192.168.1.120',
    lastActive: '2 hours ago',
    availableActions: ['Wake on LAN', 'Run background build', 'Sync repositories'],
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'JARVIS Reminder',
    message: 'Your meeting Team Standup starts in 15 minutes.',
    timestamp: '10 mins ago',
    isRead: false,
    type: 'calendar',
  },
  {
    id: 'notif-2',
    title: 'Task Update',
    message: 'Rahul completed API Integration milestone.',
    timestamp: '35 mins ago',
    isRead: false,
    type: 'task',
  },
  {
    id: 'notif-3',
    title: 'Action Required',
    message: 'You have 2 overdue tasks that require rescheduling.',
    timestamp: '1 hour ago',
    isRead: false,
    type: 'task',
  },
  {
    id: 'notif-4',
    title: 'Schedule Optimization',
    message: 'Your 4:00 PM meeting was recommended to move to 4:30 PM due to a conflict.',
    timestamp: '2 hours ago',
    isRead: true,
    type: 'calendar',
  },
  {
    id: 'notif-5',
    title: 'HRMS Sprint Metric',
    message: 'Your team sprint is currently 82% complete.',
    timestamp: '3 hours ago',
    isRead: true,
    type: 'hrms',
  },
];

export const initialIntegrations: IntegrationServiceItem[] = [
  {
    id: 'int-1',
    name: 'Google Calendar',
    description: 'Real-time schedule synchronization & smart conflict resolution.',
    category: 'Workspace',
    connected: true,
    iconName: 'Calendar',
    lastSync: '1 min ago',
  },
  {
    id: 'int-2',
    name: 'Google Meet',
    description: 'One-click meeting creation, AI agenda tracking, and join links.',
    category: 'Workspace',
    connected: true,
    iconName: 'Video',
    lastSync: 'Real-time',
  },
  {
    id: 'int-3',
    name: 'Gmail & Workspace',
    description: 'Email summarization, thread parsing, and proactive alerts.',
    category: 'Workspace',
    connected: true,
    iconName: 'Mail',
    lastSync: '5 mins ago',
  },
  {
    id: 'int-4',
    name: 'HRMS & Team Portal',
    description: 'Sprint tracking, employee metrics, leave approvals, and standups.',
    category: 'HR',
    connected: true,
    iconName: 'Users',
    lastSync: 'Just now',
  },
  {
    id: 'int-5',
    name: 'Desktop Remote Agent',
    description: 'System-level command execution: Open VS Code, Terminal, Browser, Lock.',
    category: 'Hardware',
    connected: true,
    iconName: 'Laptop',
    lastSync: 'Connected',
  },
  {
    id: 'int-6',
    name: 'Android Mobile Daemon',
    description: 'Device battery telemetry, push notifications, and quick relay.',
    category: 'Hardware',
    connected: true,
    iconName: 'Smartphone',
    lastSync: 'Connected',
  },
];

export const initialVoiceSettings: VoiceSettings = {
  voiceName: 'JARVIS Neural Core (Natural)',
  voiceSpeed: 1.05,
  voicePitch: 0.95,
  autoSpeak: true,
  wakeWordEnabled: true,
  wakeWord: 'Hey JARVIS',
  continuousListening: false,
  responseVolume: 90,
};

export const initialSecurityPermissions: SecurityPermissions = {
  lowRiskAutoExecute: true,
  mediumRiskConfirmation: true,
  highRiskConfirmation: true,
};

export const initialProductivityMetrics: ProductivityMetric[] = [
  { date: 'Mon', productivityScore: 78, focusHours: 5.2, meetingHours: 2.5, tasksCompleted: 8 },
  { date: 'Tue', productivityScore: 84, focusHours: 6.0, meetingHours: 2.0, tasksCompleted: 11 },
  { date: 'Wed', productivityScore: 72, focusHours: 4.8, meetingHours: 3.5, tasksCompleted: 6 },
  { date: 'Thu', productivityScore: 92, focusHours: 7.1, meetingHours: 1.5, tasksCompleted: 14 },
  { date: 'Fri', productivityScore: 87, focusHours: 6.4, meetingHours: 2.0, tasksCompleted: 12 },
  { date: 'Sat', productivityScore: 60, focusHours: 2.5, meetingHours: 0.5, tasksCompleted: 3 },
  { date: 'Sun', productivityScore: 55, focusHours: 2.0, meetingHours: 0.0, tasksCompleted: 2 },
];

export const initialChatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'jarvis',
    text: "Good Afternoon, Harsh. I have verified your schedule, active devices, and engineering sprint. Your next meeting is Team Standup at 10:00 AM on Google Meet. How may I assist you today?",
    timestamp: '12:00 PM',
  },
];
